config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings
from notes.api import api

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', api.urls),
    path('', include('notes.urls', namespace='notes')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

notes/urls.py
from django.urls import path
from . import views

app_name = 'notes'
urlpatterns = [
    path('', views.home, name='home'),
    path('category/<category_id>/', views.category_detail, name='detail'),
]

notes/models.py
from django.db import models

class Category(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=300)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Категории'
        ordering = ['created']

    def __str__(self):
        return self.title


class Note(models.Model):
    title = models.CharField(max_length=250)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='notes')
    created = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False, blank=True)

    class Meta:
        verbose_name_plural = 'Заметки'
        ordering = ['-created']

    def __str__(self):
        return self.title

notes/views.py
from django.shortcuts import render, get_object_or_404

from notes.models import Category


def home(request):
    return render(request, 'index.html', {'categories': Category.objects.all()})

def category_detail(request, category_id: int):
    category = get_object_or_404(Category, id=category_id)
    return render(request, 'detail.html', {'category': category})

notes/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
</head>
<body>
<div class="container-fluid header bg-dark">
    <div class="pt-5 py-5">
      <h1 class="display-5 fw-bold"><a href="{% url 'notes:home' %}" style="text-decoration: none; color: #fff;"><i class="uil uil-file-edit-alt"></i> Приложение Notes</a></h1>
             <p class="fs-5 mb-4 text-secondary">написано на Django, Django-Ninja, Alpine.js, Axios и Bootstrap</p>
    </div>
  </div>

{% block content %}
{% endblock %}
</body>
</html>

notes/templates/detail.html
{% extends "base.html" %}
{% block title %}
{{ category.title }} - все заметки
{% endblock %}
{% block content %}


<div x-data="getNotes()">
    <h3 class="text-center mt-5" style="color:#777">заметки в категории <span class="fw-bold">{{ category.title }}</span></h3>
    <form id="note-form">
        {% csrf_token %}
    </form>
    <div class="container pt-5">
        <div class="input-group px-5">
            <input x-model="newNote" class="form-control" placeholder="Текст заметки">
            <button @click="addNote(newNote, {{ category.id }} )" class="btn btn-primary"><i class="uil uil-notes"></i> Добавить заметку</button>
        </div>
    </div>
    <div class="container pt-5">
        <div class="card-group p-5">
            <div class="row row-cols-1 row-cols-md-3 g-4">
                <template x-for="note in notes">
                    <div class="col">
                        <div class="card h-100 bg-light mb-3">
                            <div class="card-header">
                <button @click="removeNote(note.id)" class="btn btn-danger"><i class="uil uil-trash-alt"></i> Удалить</button></div>
                            <div class="card-body">
                                <p x-text="note.title" class="card-text pt-3 pb-3"></p>
                            </div>
                            <div class="card-footer">
                                <button @click="updateNote(note.id, false)"
                        x-show="note.status == 'True'" class="btn btn-success float-end"><i class="uil uil-check"></i> Сделано</button>
                                <button @click="updateNote(note.id, true)"
                        x-show="note.status == 'False'" class="btn btn-warning float-end"><i class="uil uil-rocket"></i> В процессе</button>
                            </div>
                        </div>
                    </div>
                </template>
            </div>
        </div>
    </div>
</div>


<script>

    const csrftoken = document.querySelector('#note-form > input').value;


    const getNotes = () => {
        return {
            newNote: '',
            notes: [
            {% for note in category.notes.all %}
            { 'title': '{{ note.title }}', 'id': '{{ note.id }}', 'status': '{{ note.completed }}' },
            {% endfor %}
    ]
    }
    };

    const addNote = async (title, categoryId) => {
        try {
            const res = await axios.post('/api/notes',
        { title, category_id: categoryId },
        { headers: { 'X-CSRFToken': csrftoken }}
            );
            location.reload();
        } catch (e) {
            console.error(e);
        }
    };

    const removeNote = async noteId => {
        try {
            const res = await axios.delete('/api/notes/' + noteId,
        { headers: { 'X-CSRFToken': csrftoken }}
            );
            location.reload();
        } catch (e) {
            console.error(e);
        }
    };

    const updateNote = async (noteId, noteStatus) => {
        try {
            const res = await axios.patch('/api/notes/' + noteId,
        { id: noteId, completed: noteStatus},
        { headers: { 'X-CSRFToken': csrftoken }}
            );
            location.reload();
        } catch (e) {
            console.error(e);
        }
    };


</script>

{% endblock %}

notes/templates/index.html
{% extends "base.html" %}

{% block title %}
Приложение Notes
{% endblock %}

{% block content %}


<div x-data="getCategories()">
   <h3 class="text-center mt-5" style="color:#777">все категории заметок пользователя <span class="fw-bold">{{ request.user.username }}</span></h3>
    <form id="category-form">
        {% csrf_token %}
    </form>
    <div class="container pt-5">
        <div class="input-group px-5">
            <input x-model="newCategory" class="form-control" placeholder="Название категории">
            <input x-model="newDescription" class="form-control" placeholder="Описание категории">
  <button @click="addCategory(newCategory, newDescription)" type="button" class="btn btn-primary"><i class="uil uil-notes"></i> Добавить категорию</button>
        </div>
        <div class="card-group p-5">
            <div class="row row-cols-1 row-cols-md-3 g-4">
                <template x-for="category in categories">
                    <div class="col">
                        <div class="card h-100 bg-light">
                            <div class="card-header">
                                <h4 class="card-title text-center my-2"><a x-text="category.title"
         x-bind:href="'/category/'+category.id"></a></h4>
                            </div>
                            <div class="card-body">
                                <p x-text="category.description" class="card-text pt-3 pb-3"></p>
                            </div>
                            <div class="card-footer">
                                <button type="button" class="btn btn-primary btn-sm">
       <a x-bind:href="'/category/'+category.id" style="text-decoration: none; color:#fff;"><i class="uil uil-search"></i> Открыть</a>
                                    <button @click="removeCategory(category.id)"
         class="btn btn-danger btn-sm float-end"><i class="uil uil-trash-alt"></i> Удалить</button>
                            </div>
                        </div>
                    </div>
                </template>
            </div>
        </div>


    </div>
</div>
<script>


    const getCategories = () => {
        return {
            newCategory: '',
            newDescription: '',
            categories: [
            {% for category in categories %}
            { 'title': '{{ category.title }}', 'id': '{{ category.id }}', 'description': '{{ category.description }}' },
            {% endfor %}
    ]
    }
    };

    const csrftoken = document.querySelector('#category-form > input').value;


    const addCategory = async (title, description) => {
        try {
            const res = await axios.post('/api/category',
        { title, description },
        { headers: { 'X-CSRFToken': csrftoken }}
            );
            location.reload();
        } catch (e) {
            console.error(e);
        }
    };

    const removeCategory = async categoryId => {
        try {
            const res = await axios.delete('/api/category/' + categoryId,
        { headers: { 'X-CSRFToken': csrftoken }}
            );
            location.reload();
        } catch (e) {
            console.error(e);
        }
    };

</script>

{% endblock %}